/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qHCPhZCGJHC
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function hero() {
  return (
    <div className="bg-white text-gray-900">
      <header className="flex items-center justify-between p-4 border-b">
        <div className="flex items-center space-x-2">
          <FacebookIcon className="text-blue-600 h-6 w-6" />
          <h1 className="text-xl font-semibold">Jahir Fiquitiva</h1>
        </div>
        <nav className="flex space-x-4">
          <Link className="text-blue-600 hover:underline" href="#">
            About
          </Link>
          <Link className="text-blue-600 hover:underline" href="#">
            Blog
          </Link>
          <Link className="text-blue-600 hover:underline" href="#">
            Projects
          </Link>
          <Link className="text-blue-600 hover:underline" href="#">
            Uses
          </Link>
          <SettingsIcon className="text-gray-600 h-6 w-6" />
        </nav>
      </header>
      <main className="px-4 py-8">
        <section className="mb-8">
          <h2 className="text-3xl font-bold mb-2">👋 Hola, mundo!</h2>
          <h3 className="text-2xl font-semibold mb-4">
            I am Jahir Fiquitiva <BadgeIcon className="text-blue-600 h-6 w-6 inline" />
          </h3>
          <p className="mb-4">
            Passionate and creative full-stack software engineer from Colombia{" "}
            <span aria-label="flag" role="img">
              🇨🇴
            </span>
          </p>
          <p className="mb-4">
            Detail-driven, I strive to build great-looking, user-friendly software while enhancing my skills along the
            way
          </p>
          <Button className="bg-blue-600 text-white">More about me</Button>
          <div className="flex space-x-4 mt-4">
            <GithubIcon className="text-gray-600 h-6 w-6" />
            <LinkedinIcon className="text-blue-700 h-6 w-6" />
            <SlackIcon className="text-pink-500 h-6 w-6" />
            <InstagramIcon className="text-pink-400 h-6 w-6" />
            <MailIcon className="text-gray-600 h-6 w-6" />
          </div>
        </section>
        <section>
          <div className="flex items-center justify-between mb-4">
            <h4 className="text-xl font-semibold">From the blog</h4>
            <div className="flex items-center space-x-2">
              <RssIcon className="text-orange-500 h-6 w-6" />
              <Button className="bg-blue-600 text-white">RSS Feed</Button>
              <Button className="bg-blue-600 text-white">View all</Button>
            </div>
          </div>
          <div className="grid gap-4">
            <article className="flex items-center space-x-4">
              <img
                alt="Blog post"
                className="h-24 w-24 object-cover"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
              <div>
                <h5 className="font-semibold">How Tailwind CSS grew on me</h5>
                <p className="text-sm text-gray-600">A journey turning skepticism and dislike into enthusiasm</p>
                <p className="text-sm text-gray-600">March 02, 2024 · 5 min read · 734 views</p>
              </div>
            </article>
            <article className="flex items-center space-x-4">
              <img
                alt="Blog post"
                className="h-24 w-24 object-cover"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
              <div>
                <h5 className="font-semibold">Things you can do to get started with development</h5>
                <p className="text-sm text-gray-600">
                  Tips, resources and ideas to get into coding and learning by yourself
                </p>
                <p className="text-sm text-gray-600">January 01, 2022 · 5 min read · 1187 views</p>
              </div>
            </article>
            <article className="flex items-center space-x-4">
              <img
                alt="Blog post"
                className="h-24 w-24 object-cover"
                height="100"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "100/100",
                  objectFit: "cover",
                }}
                width="100"
              />
              <div>
                <h5 className="font-semibold">Direct download any Xcode</h5>
                <p className="text-sm text-gray-600">
                  Tired of interrupted Xcode downloads? Resume them seamlessly with a quick trick
                </p>
                <p className="text-sm text-gray-600">October 27, 2018 · 2 min read · 571 views</p>
              </div>
            </article>
          </div>
        </section>
      </main>
    </div>
  )
}


function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function BadgeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
    </svg>
  )
}


function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function SlackIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="3" height="8" x="13" y="2" rx="1.5" />
      <path d="M19 8.5V10h1.5A1.5 1.5 0 1 0 19 8.5" />
      <rect width="3" height="8" x="8" y="14" rx="1.5" />
      <path d="M5 15.5V14H3.5A1.5 1.5 0 1 0 5 15.5" />
      <rect width="8" height="3" x="14" y="13" rx="1.5" />
      <path d="M15.5 19H14v1.5a1.5 1.5 0 1 0 1.5-1.5" />
      <rect width="8" height="3" x="2" y="8" rx="1.5" />
      <path d="M8.5 5H10V3.5A1.5 1.5 0 1 0 8.5 5" />
    </svg>
  )
}


function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function RssIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 11a9 9 0 0 1 9 9" />
      <path d="M4 4a16 16 0 0 1 16 16" />
      <circle cx="5" cy="19" r="1" />
    </svg>
  )
}
